FROM jenkins/jenkins:lts
USER root

# Docker CLI Statik Kurulumu
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-27.3.1.tgz && \
    tar xzvf docker-27.3.1.tgz && \
    mv docker/docker /usr/local/bin/ && \
    rm -rf docker docker-27.3.1.tgz

# Docker Compose Eklentisi Kurulumu
RUN mkdir -p /usr/local/libexec/docker/cli-plugins && \
    curl -SL https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-x86_64 -o /usr/local/libexec/docker/cli-plugins/docker-compose && \
    chmod +x /usr/local/libexec/docker/cli-plugins/docker-compose && \
    ln -s /usr/local/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose

# Jenkins kullanıcısına geri dön
USER jenkins
